# Generated by Django 3.0.2 on 2020-02-21 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('add_hubs', '0003_auto_20200221_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='received',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_datetime', models.DateTimeField()),
                ('hub_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_hubs.hubs')),
            ],
        ),
    ]
