# Generated by Django 3.0.2 on 2020-02-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCSEST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PCSEST_E2_17', models.IntegerField(blank=True)),
                ('PCSEST_E2_CRUZADO', models.IntegerField(blank=True)),
                ('PCSEST_E1_MEDIO', models.IntegerField(blank=True)),
                ('PCSEST_E3_ENTRADA', models.IntegerField(blank=True)),
                ('PCSEST_E3_14', models.IntegerField(blank=True)),
                ('PCSEST_B1_21', models.IntegerField(blank=True)),
                ('PCSEST_B1_19', models.IntegerField(blank=True)),
                ('PCSEST_B1_20', models.IntegerField(blank=True)),
                ('PCSEST_B1_23', models.IntegerField(blank=True)),
                ('PCSEST_A1_8', models.IntegerField(blank=True)),
                ('PCSEST_A1_MEDIO', models.IntegerField(blank=True)),
                ('PCSEST_A1_9', models.IntegerField(blank=True)),
                ('PCSEST_C1_10', models.IntegerField(blank=True)),
                ('PCSEST_A2_1', models.IntegerField(blank=True)),
                ('PCSEST_C1_24', models.IntegerField(blank=True)),
                ('PCSEST_C1_11', models.IntegerField(blank=True)),
                ('PCSEST_C2_4', models.IntegerField(blank=True)),
                ('PCSEST_C2_6', models.IntegerField(blank=True)),
                ('PCSEST_A2_3', models.IntegerField(blank=True)),
                ('PCSEST_EURO_N1', models.IntegerField(blank=True)),
                ('PCSEST_EURO_N2', models.IntegerField(blank=True)),
                ('MAC', models.CharField(max_length=17)),
                ('fechahora', models.DateTimeField()),
                ('Zona', models.CharField(max_length=50)),
            ],
        ),
    ]
