# Generated by Django 3.0.2 on 2020-02-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_data', '0003_auto_20200224_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcsest',
            name='PCSEST_A1_8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pcsest',
            name='PCSEST_A1_9',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pcsest',
            name='PCSEST_A1_MEDIO',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pcsest',
            name='PCSEST_A2_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pcsest',
            name='PCSEST_A2_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pcsest',
            name='PCSEST_B1_19',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pcsest',
            name='PCSEST_B1_20',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pcsest',
            name='PCSEST_B1_21',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pcsest',
            name='PCSEST_B1_23',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pcsest',
            name='PCSEST_C1_10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pcsest',
            name='PCSEST_C1_11',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pcsest',
            name='PCSEST_C1_24',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pcsest',
            name='PCSEST_C2_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pcsest',
            name='PCSEST_C2_6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pcsest',
            name='PCSEST_E1_MEDIO',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pcsest',
            name='PCSEST_E2_17',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pcsest',
            name='PCSEST_E2_CRUZADO',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pcsest',
            name='PCSEST_E3_14',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pcsest',
            name='PCSEST_E3_ENTRADA',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pcsest',
            name='PCSEST_EURO_N1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pcsest',
            name='PCSEST_EURO_N2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
