# Generated by Django 3.0.2 on 2020-03-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_data', '0005_auto_20200225_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcsest',
            name='fechahora',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
