# Generated by Django 3.0.2 on 2020-03-23 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_data', '0006_auto_20200311_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechahora', models.DateTimeField(blank=True, null=True)),
                ('MAC', models.CharField(max_length=17)),
                ('rssi', models.FloatField(blank=True, null=True)),
                ('evento', models.CharField(max_length=50)),
            ],
        ),
    ]
