# Generated by Django 3.0.2 on 2020-06-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_data', '0007_ipg'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCS_indoor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PCS_N1_1', models.FloatField(blank=True, null=True)),
                ('PCS_N1_18', models.FloatField(blank=True, null=True)),
                ('PCS_N1_2', models.FloatField(blank=True, null=True)),
                ('PCS_N1_3', models.FloatField(blank=True, null=True)),
                ('PCS_N1_4', models.FloatField(blank=True, null=True)),
                ('PCS_N1_5', models.FloatField(blank=True, null=True)),
                ('PCS_N1_6', models.FloatField(blank=True, null=True)),
                ('PCS_N1_7', models.FloatField(blank=True, null=True)),
                ('PCS_N2_10', models.FloatField(blank=True, null=True)),
                ('PCS_N2_11', models.FloatField(blank=True, null=True)),
                ('PCS_N2_12', models.FloatField(blank=True, null=True)),
                ('PCS_N2_8', models.FloatField(blank=True, null=True)),
                ('PCS_N2_9', models.FloatField(blank=True, null=True)),
                ('PCS_N3_14', models.FloatField(blank=True, null=True)),
                ('PCS_N3_15', models.FloatField(blank=True, null=True)),
                ('PCS_N3_16', models.FloatField(blank=True, null=True)),
                ('PCS_N3_17', models.FloatField(blank=True, null=True)),
                ('MAC', models.CharField(max_length=17)),
                ('fechahora', models.DateTimeField(blank=True, null=True)),
                ('Zona', models.CharField(max_length=50)),
            ],
        ),
    ]
