# Generated by Django 3.0.2 on 2020-06-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_data', '0008_pcs_indoor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcs_indoor',
            name='Probability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pcsest',
            name='Probability',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
