# Generated by Django 3.0.2 on 2020-06-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_data', '0009_auto_20200607_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcs_indoor',
            name='PCS_N2_13',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
