# Generated by Django 3.0.2 on 2020-02-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hubs',
            fields=[
                ('hub_id', models.AutoField(primary_key=True, serialize=False)),
                ('hub_name', models.CharField(max_length=50)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
