# Generated by Django 3.0.2 on 2020-02-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_hubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubs',
            name='hub_ml_model',
            field=models.CharField(default='temp', max_length=50),
            preserve_default=False,
        ),
    ]
