# Generated by Django 3.0.2 on 2020-02-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_hubs', '0002_hubs_hub_ml_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hubs',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='hubs',
            name='hub_id',
        ),
        migrations.RemoveField(
            model_name='hubs',
            name='hub_ml_model',
        ),
        migrations.AlterField(
            model_name='hubs',
            name='hub_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
